name: Find most recent File changed
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
jobs:
  find-changed-file:
      name: Find the file that was updated most recently
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - name: Run a multi-line script
          run: |
            ls -lah
            ls -tl *.conf | head -n1
        - id: file_changes
          uses: trilom/file-changes-action@v1.2.3
          with:
            output: 'json'
        - name: test
          run: |
            echo ${{steps.file_changes.outputs.files_modified}}