name: Find most recent File changed
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
jobs:
  find-changed-file:
      name: Find the file that was updated most recently
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - name: Fetch the config file that was modified most recently 
          id: extract-fname
          run: |
            echo "::set-output name=recent-file::$(ls -tl *.conf | head -n1)"
        - name: Generate something
          run: |
            echo ${{steps.extract-fname.outputs.recent-file}}